## service definition
version:"3.3"
services:
  webserver:
    image:ubuntu
    ports:
      -"80:80"
    networks:
      -webnet
    
  redis:
    image: redis
    networks:
      -webnet

# Network Definition
network:
  webnet:

## Data Volume Definition
Volumes:
  data-volume:

## Container link
links:
  - logserver
  - logserver:log01

## Ports
ports:
  - "3000"
  - "8000:80"
  - "127.9.0.1:8000:8000"  


## exposes
expose:
  - "3000"
  
 #예시이므로 실행은 안함, 템플릿처럼 사용하길. 